//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTech.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class banner
    {
        public long id { get; set; }
        public string banner_title { get; set; }

        [Required(ErrorMessage = "Banner description is required")]
        public string banner_description { get; set; }

        [Required(ErrorMessage = "Banner Image is required")]
        public string banner_image { get; set; }
    }
}
