//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaign
    {
        public long id { get; set; }
        public string campaign_for { get; set; }
        public string campaign_name { get; set; }
        public string campaign_image { get; set; }
        public string image_type { get; set; }
        public int percentage { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime end { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
