//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public long id { get; set; }
        public string address { get; set; }
        public long shipping_id { get; set; }
        public decimal price { get; set; }
        public string status { get; set; }
        public long user_id { get; set; }
        public string order_id { get; set; }
    
        public virtual shipping shipping { get; set; }
        public virtual user user { get; set; }
    }
}
